### ISSUE TITLE
Banyak exception

### ISSUE THREAD

**Issue by baddwin** [balitax/SI-Sekolah-L5#2]
Mohon bimbingannya.
saya sudah clone, `composer update`, impor database dengan phpmyadmin dan `php artisan migrate`, `php artisan serve`, buka browser `localhost:8000` langsung dapat exception kolom `kategori_berita` tidak ada di _tbl_berita_, saya tambahkan manual. Lalu refresh page, keluar exception lagi

```
PHP Fatal error:  Class 'App\Models\Banner' not found in .../SI-Sekolah-L5/app/Http/Controllers/FrontController.php on line 42
```

**Comment by baddwin** [comment]
Apakah mungkin beberapa file tidak di-track dalam GIt?

Error lainnya semisal:
`View [bappeda.berita_detail] not found.`

Pasalnya tidak ada folder `bappeda` dalam `resources/views`

**Comment by maful** [comment]
Hai @baddwin silahkan ganti `bappeda` menjadi `web`
kemudian ubah `berita_detail` menjadi `beritadetail`

**Comment by maful** [comment]
@baddwin kemungkinan ada beberapa tabel dan models yang tidak di upload ke git
solusi sementara yang saya lakukan adalah mengubah line pada beberapa models yang tidak ada menjadi komentar ( Sublime Linux Ctrl+/ )

**Comment by balitax** [comment]
Hy All, mohon maaf repo ini sudah tidak saya lanjutkan lagi pengerjaannya. atau mungkin jika ada yang berminat memperbaiki saya persilahkan

**Comment by harimayco** [comment]
sayang sekali padahal bagus bgt ini tapi gak bisa dipakai karna databasenya banyak yg hilang.

**Comment by balitax** [comment]
iya gan @harimayco , mau benerin udah lupa sama laravel. lama g mainan Php

**Comment by maful** [comment]
mas @balitax saya berminta untuk bantu pengembangan, kemudian untuk CONTRIBUTING GUIDE nya bagaimana?
